export const ORDER_STATUS = {
    ALL: "ALL",
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SHIPPING: "SHIPPING",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    FAILED: "FAILED",
}